version: '3'

services:
    db:
      image: postgres
      ports:
        - "5432:5432"
    web:
        build: .
        env_file:
            - docker.env
        command:  bash -c "cd project/ && python3 manage.py runserver 0.0.0.0:8000"
        container_name: API
        volumes:
            - .:/API
        ports:
            - "8000:8000"
        depends_on:
            - db